atividadeativa/atividadeativa/urls.py
from django.contrib import admin
from django.urls import path, include
from backend.urls import *

urlpatterns = [
    path('', include('backend.urls')),
    path('admin/', admin.site.urls),
]

atividadeativa/backend/urls.py
from django.urls import path
from . import views

app_name='backend'

urlpatterns = [
    path('', views.index, name='index'),
    path('results/<int:question_id>', views.results, name='results'),
    path('vote/<int:question_id>', views.vote, name='vote'),
]

atividadeativa/backend/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
  text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date_published')

class Option(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

atividadeativa/backend/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question

# Create your views here.


def index(req):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(req, 'backend/index.html', context)


def results(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(req, 'backend/results.html', context)


def vote(req, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if req.method == 'POST':
        try:
            print('Recuperando opção')
            print(req.POST)
            selected_choice = question.option_set.get(pk=(int(req.POST['option']) + 1))
        except KeyError:
            print('Erro')
            return render(req, 'backend/vote.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            print('Sucesso')
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('backend:results', args=(question_id,)))
    else:
        context = {'question': question}
        return render(req, 'backend/vote.html', context)

atividadeativa/backend/templates/backend/index.html
{% load static %}
<div>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <header>
    <h1>Rodízio de Pizza</h1>
  </header>
  <main>
    {% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
          <li>
            <a href="{% url 'backend:vote' question.id %}">{{ question.text }}</a>
          </li>
        {% endfor%}
      </ul>

    {% else %}
      <p>Não há perguntas</p>  

    {% endif %}

  </main>

  <footer>Gabriel Trindade - 2186101052</footer>
</div>

atividadeativa/backend/templates/backend/results.html
{% load static %}
<div>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <header>
    <h1>Rodízio de Pizza</h1>
  </header>
  <main>
    <div style="padding: 1em;">
      {% csrf_token %}
      {% if question %}
      <h2>{{ question.text }}</h2>
      <ul>
        {% for option in question.option_set.all %}
        <li>
          <p>{{ option.text }}</p>
          <div style="background-color: black; height: {{ option.votes }}em; width: 1em"></div>
        </li>
        {% endfor%}
      </ul>

      {% else %}
      <p>Erro ao carregar pergunta</p>

      {% endif %}

    </div>
    <div class="botoes">
      <a href="{% url 'backend:index' %}">Página inicial</a>
    </div>
  </main>
  <footer>Gabriel Trindade - 2186101052</footer>
</div>

atividadeativa/backend/templates/backend/vote.html
{% load static %}
<div>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <header>
    <h1>Rodízio de Pizza</h1>
  </header>
  <main>
    <div style="padding: 1em;">

      <form action="{% url 'backend:vote' question.id %}" method="post">
        {% csrf_token %}
        <h2>{{ question.text }}</h2>
        <div style="padding: 1em;">
          {% for option in question.option_set.all %}

          <input id="{{option.id}}" type="radio" value="{{option.text}}" name="option" />
          <label for="{{option.text}}">{{option.text}}</label>

          {% endfor %}

        </div>
        <input type="submit" value="Enviar"></input>

      </form>

    </div>

    <div class="botoes">
      <a href="{% url 'backend:index' %}">Página inicial</a>
      <a href="{% url 'backend:results' question.id %}">Acompanhe os resultados</a>
    </div>

  </main>
  <footer>Gabriel Trindade - 2186101052</footer>
</div>